language: generic
notifications:
  email:
    on_success: change
    on_failure: always

services:
  - docker

git:
  quiet: true

env:
  matrix:
    - ROS_DISTRO=kinetic
    - ROS_DISTRO=kinetic PRERELEASE=true

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
  - .industrial_ci/travis.sh
